version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: currenjin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
      MYSQL_USER: spring
      MYSQL_PASSWORD: book
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
