# docker-compose.yml

version: "3"
services:
  post:
    container_name: post
    restart: always
    ports:
      - "5001:8080"
    environment:
      - POST_QUEUE_NAME=post-queue
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=myuser
      - SPRING_RABBITMQ_PASSWORD=secret
    build:
      context: ./post/
      dockerfile: Dockerfile
    depends_on:
      - rabbit-mq

  delivery:
    container_name: delivery
    restart: always
    ports:
      - "5002:8080"
    environment:
      - POST_QUEUE_NAME=post-queue
      - DELIVERY_QUEUE_NAME=delivery-queue
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=myuser
      - SPRING_RABBITMQ_PASSWORD=secret
    build:
      context: ./delivery/
      dockerfile: Dockerfile
    depends_on:
      - rabbit-mq

  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'