spring:
  application:
    name: delivery

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret


post:
  queue:
    name: ${POST_QUEUE_NAME}
delivery:
  queue:
    name: ${DELIVERY_QUEUE_NAME}
